FROM python:3.11-slim
WORKDIR /app
COPY backend/ ./backend/
COPY backend/models/ ./backend/models/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENV PORT=5000
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "backend.app:app"]